version: '3'
services:
  backend:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/src/app
      - exclude:/usr/src/app/node_modules
    ports:
      - "3001:3001"
    environment:
      DATABASE_USER: milica
      DATABASE_PASSWORD: Milly987!
      DATABASE_NAME: mydatabase
      DATABASE_HOST: database
      DATABASE_PORT: 3306
    depends_on:
      - database
      - elasticsearch
      - kibana
    command: "dockerize -wait tcp://database:3306 -timeout 300s -wait-retry-interval 3s npm run start:dev"

  database:
    image: mysql
    volumes:
      - ./environment/database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Milly987!
      MYSQL_USER: milica
      MYSQL_PASSWORD: Milly987!
      MYSQL_DATABASE: mydatabase
    ports:
      - 3360:3306

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ./environment/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.4.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

volumes:
  exclude:
